# mavros_param.yaml
mavros:
  ros__parameters: {}

mavros_router:
  ros__parameters: {}

mavros_node:
  ros__parameters:
    fcu_url: /dev/ttyTHS0:921600
    # gcs_url: udp-b://@
    gcs_url: udp://@192.168.137.1:14550
    tgt_system: 1
    # fcu_url: /dev/ttyAMA0:921600
    # fcu_url: /dev/ttyACM0:921600
    
