# mavros_param.yaml
mavros:
  ros__parameters: {}

mavros_router:
  ros__parameters: {}

mavros_node:
  ros__parameters:
    fcu_url: /dev/ttyTHS0:921600
    tgt_system: 3
    # fcu_url: /dev/ttyAMA0:921600
    # fcu_url: /dev/ttyACM0:921600
    # gcs_url: tcp-l://:5670
